schema: src/api/graphql/generated/graphql.schema.graphql
documents:
  - src/api/graphql/generated/*.ts
extensions:
  endpoints:
    Default GraphQL Endpoint:
#      url: https://swapi-graphql.netlify.app/.netlify/functions/index
      url: https://rickandmortyapi.com/graphql
      headers:
        user-agent: JS GraphQL
        Access-Control-Allow-Origin: https://rickandmortyapi.com/graphql
#        Access-Control-Allow-Origin: https://swapi-graphql.netlify.app/.netlify/functions/index
        Access-Control-Allow-Credentials: true
      introspect: true
