schema: src/graphql/generated/graphql.schema.graphql
documents:
  - src/graphql/generated/*.ts
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:8888/
      headers:
        user-agent: JS GraphQL
        Access-Control-Allow-Origin: http://localhost:8888/
        Access-Control-Allow-Credentials: true
      introspect: true
